
/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { InsightCartridge } from "./insight-object";

/**
 * SYSTEM SERIALIZER (The "Export" Engine)
 * Transforms the Insight Cartridge JSON state into a deployable Python AI Agent.
 * 
 * IFR-1: "The workspace IS the system."
 */

export const generatePythonAgent = (cartridge: InsightCartridge): string => {
    const strategy = cartridge.quadrants.strategy;
    const creative = cartridge.quadrants.creative;
    const producing = cartridge.quadrants.producing;
    const media = cartridge.quadrants.media;
    const hero = cartridge.hero;
    const villain = cartridge.villain;

    return `
import os
import json
from google.genai import GoogleGenAI

# --- INDRA SYSTEM ARCHITECTURE: ${cartridge.id} ---
# AUTO-GENERATED BY INDRA-AI.DEV

class SystemConfig:
    """ Core Configuration Matrix """
    HERO = "${hero.name} - ${hero.description || 'Undefined'}"
    VILLAIN = "${villain.name} - ${villain.description || 'Undefined'}"
    
    # Quadrant Integrity Levels
    STRATEGY_LEVEL = ${strategy.level}
    CREATIVE_LEVEL = ${creative.level}
    PRODUCING_LEVEL = ${producing.level}
    MEDIA_LEVEL = ${media.level}

class StrategyEngine:
    """ Quadrant 1: The Brain """
    def __init__(self):
        self.status = "${strategy.status}"
    
    def analyze_vector(self, context):
        # Placeholder for strategic logic based on user notes
        return f"Optimizing path for {SystemConfig.HERO}..."

class CreativeEngine:
    """ Quadrant 2: The Soul """
    def __init__(self):
        self.status = "${creative.status}"

    def generate_asset(self, type):
        return f"Generating {type} asset..."

class ProducingEngine:
    """ Quadrant 3: The Hands """
    def __init__(self):
        self.status = "${producing.status}"

    def allocate_resources(self):
        return "Resources allocated."

class MediaEngine:
    """ Quadrant 4: The Voice """
    def __init__(self):
        self.status = "${media.status}"

    def broadcast(self, message):
        return f"Broadcasting: {message}"

class AutonomousAgent:
    def __init__(self):
        self.api_key = os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            print("WARNING: GEMINI_API_KEY not found. Agent running in simulation mode.")
            self.client = None
        else:
            self.client = GoogleGenAI(api_key=self.api_key)
        
        # Initialize Sub-Systems
        self.strategy = StrategyEngine()
        self.creative = CreativeEngine()
        self.producing = ProducingEngine()
        self.media = MediaEngine()
        
        self.system_instruction = f"""
        You are the INDRA SYSTEM for {SystemConfig.HERO}.
        Your objective is to overcome {SystemConfig.VILLAIN}.
        
        OPERATIONAL MODES:
        - STRATEGY ({SystemConfig.STRATEGY_LEVEL}%): Focus on long-term goals.
        - CREATIVE ({SystemConfig.CREATIVE_LEVEL}%): Focus on innovation.
        - PRODUCING ({SystemConfig.PRODUCING_LEVEL}%): Focus on execution.
        - MEDIA ({SystemConfig.MEDIA_LEVEL}%): Focus on messaging.
        """

    def execute(self, user_input):
        # In a real deployment, this would call the LLM with specific tools based on the input
        if self.client:
            try:
                response = self.client.models.generate_content(
                    model='gemini-2.5-flash',
                    contents=user_input,
                    config={
                        'system_instruction': self.system_instruction
                    }
                )
                return response.text
            except Exception as e:
                return f"API ERROR: {e}"
        else:
            return f"[SIMULATION] Agent received: {user_input}"

if __name__ == "__main__":
    agent = AutonomousAgent()
    print(f"INDRA SYSTEM {cartridge.id} ONLINE.")
    print(f"MISSION: {SystemConfig.HERO}")
    print(f"OBSTACLE: {SystemConfig.VILLAIN}")
    
    while True:
        try:
            user_in = input("COMMAND> ")
            if user_in.lower() in ['exit', 'quit']:
                break
            print(agent.execute(user_in))
        except KeyboardInterrupt:
            break
`;
};

export const generateRequirements = (): string => {
    return `google-genai>=1.0.0
python-dotenv
`;
};

export const generateReadme = (cartridge: InsightCartridge): string => {
    return `# INDRA SYSTEM EXPORT: ${cartridge.id}

## Insight Systematization
This agent was auto-generated by indra-ai.dev based on the following 4-Quadrant analysis:

| Quadrant | Status | Integrity |
|----------|--------|-----------|
| Strategy | ${cartridge.quadrants.strategy.status} | ${cartridge.quadrants.strategy.level}% |
| Creative | ${cartridge.quadrants.creative.status} | ${cartridge.quadrants.creative.level}% |
| Producing| ${cartridge.quadrants.producing.status}| ${cartridge.quadrants.producing.level}%|
| Media    | ${cartridge.quadrants.media.status}    | ${cartridge.quadrants.media.level}%   |

## Architecture
The agent is structured into four modular classes corresponding to the quadrants of the Indra framework.

## Deployment

1. Install dependencies:
   \`pip install -r requirements.txt\`

2. Set API Key:
   \`export GEMINI_API_KEY=your_key_here\`

3. Run Agent:
   \`python main.py\`
`;
};

/**
 * Simulates a ZIP download by creating a Blob from the text content.
 * In a real app, we'd use JSZip, but this demonstrates the "Artifact Generation" function.
 */
export const triggerDownload = (filename: string, content: string) => {
    const element = document.createElement('a');
    const file = new Blob([content], {type: 'text/plain'});
    element.href = URL.createObjectURL(file);
    element.download = filename;
    document.body.appendChild(element); // Required for this to work in FireFox
    element.click();
    document.body.removeChild(element);
};
